// Code generated by "stringer -type=MessageType --linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessagePlain-0]
	_ = x[MessageExtended-1]
	_ = x[MessageUnknown-2]
}

const _MessageType_name = "MessagePlainMessageExtendedMessageUnknown"

var _MessageType_index = [...]uint8{0, 12, 27, 41}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
